# compose.yaml
# This is the compose.yaml file for running the docker compose

services:
  core_app:
    build:
      context: .
      dockerfile: Dockerfile.core_app
      args:
        APP_PORT: ${APP_PORT}
        APP_DIR: ${APP_DIR}
    restart: always
    env_file:
      - ".env"
      - ".env.webapp"
    # i will not use port open because caddy will do this for me
    # ports:
    #   - "${PUBLISH_PORT}:${APP_PORT}"
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:${APP_PORT}/health-check')" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

    depends_on:
      database:
        condition: service_healthy
        restart: true
        required: true

  database:
    # image: postgres:18.4-bookworm
    image: postgres:18.4-bookworm

    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    healthcheck:
      # test: [ "CMD-SHELL", "pg_isready" ]
      # test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ] # This will not work also
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

    ports:
      # i am exposing this port just for now in devleopment
      # i will do this to check some postgres data there
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  caddy:
    image: caddy:2.11.4-alpine
    restart: always
    environment:
      PUBLISH_PORT: ${PUBLISH_PORT}
      APP_PORT: ${APP_PORT}
    ports:
      - "80:80"
      - "443:443"
      - "${PUBLISH_PORT}:${PUBLISH_PORT}"

    depends_on:
      core_app:
        condition: service_healthy
        restart: true
        required: true

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
