# This is the compose.yaml file for running the docker compose

services:
  core_app:
    build:
      context: .
      dockerfile: Dockerfile.core_app

    restart: always

    volumes:
      - sqlite_data:/rana/files_and_folders

    env_file:
      - "webapp.env"

  caddy:
    image: caddy:2.11.1-alpine

    restart: unless-stopped

    ports:
      - "2026:2026"
      - "80:80"
      - "443:443"
      - "9999:9999"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  sqlite_data:
