# ./DockerFile is this file
# Below two line i got from the uv official docs

FROM python:3.14-slim-trixie

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ARG APP_DIR=/rana

WORKDIR ${APP_DIR}

COPY .python-version pyproject.toml uv.lock ./

RUN uv sync

COPY . ./

EXPOSE 8001

CMD ["uv", "run", "gunicorn", "main:app"]
