# ./DockerFile.core_app
# Below two line i got from the uv official docs

FROM python:3.14.2-slim-trixie


COPY --from=ghcr.io/astral-sh/uv:0.11.26 /uv /uvx /bin/

ARG APP_DIR=/app
ARG APP_PORT=8001

WORKDIR ${APP_DIR}

COPY .python-version pyproject.toml uv.lock ./

RUN uv sync

COPY . ./

EXPOSE ${APP_PORT}


CMD ["uv", "run", "main.py"]
